{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_Currency\",\"dim_Customer\",\"dim_SalesTerritory\",\"fact_InternetSales\",\"dim_Product\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "measures.customers": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "#Measures",
                    "ConceptualProperty": "Customers"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Number of Customers": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "measures.productssold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "#Measures",
                    "ConceptualProperty": "ProductsSold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Products Sold": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "measures.totalsalesamount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "#Measures",
                    "ConceptualProperty": "TotalSalesAmount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Sales Amount": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "25e17877-4dc6-4477-a1b6-7aac7a7521fb",
        "fromColumn": "BirthDate",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_22d855fd-72d2-47d1-83d6-ea7b18773cdc"
      },
      {
        "name": "afb763cb-5e25-436e-8758-2f1c93815b2f",
        "fromColumn": "DateFirstPurchase",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8d6ff6fd-407c-4b21-b7b2-e2fa0ecb12cd"
      },
      {
        "name": "05d3c491-d361-4c6f-872d-557738746fa6",
        "fromColumn": "OrderDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_734177d9-7e0e-49b7-92ab-36014931130a"
      },
      {
        "name": "5ee69d2e-e4b1-40f4-9c9a-ba8007210467",
        "fromColumn": "DueDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3364ad5d-e938-4ce4-b154-5dc0cc8fc6d8"
      },
      {
        "name": "1d1c9870-7f5f-45fd-a0b4-d3ff6421935f",
        "fromColumn": "ShipDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3d26bdf8-f479-4972-b8e9-407ae491cb95"
      },
      {
        "name": "f826bf6a-dd6c-45d6-8017-51773b4d452d",
        "fromColumn": "CurrencyKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CurrencyKey",
        "toTable": "dim_Currency"
      },
      {
        "name": "58be493a-cff8-4c38-8fc1-a31ee9c20a3c",
        "fromColumn": "CustomerKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CustomerKey",
        "toTable": "dim_Customer"
      },
      {
        "name": "d0ccf069-37af-4a9b-b535-0a4ea2944afa",
        "fromColumn": "SalesTerritoryKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "SalesTerritoryKey",
        "toTable": "dim_SalesTerritory"
      },
      {
        "name": "c145660d-7545-4ea1-aae7-529f067dd3fa",
        "fromColumn": "ProductKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "ProductKey",
        "toTable": "dim_Product"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "dim_Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed8c2b73-8e58-4faa-af69-fee12e23c24c",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "833c3d93-fc4a-48cb-a083-32214c013d14",
            "sourceColumn": "CurrencyAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bedf8df-5d09-4dc5-9732-e4636fc19519",
            "sourceColumn": "CurrencyName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b3dfc036-331b-43d4-ae6a-b318fb2f6ddb",
        "partitions": [
          {
            "name": "dim_Currency",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\365 Data Science Power BI\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Currency_Sheet = Source{[Item=\"dim_Currency\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Currency_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CurrencyKey\", Int64.Type}, {\"CurrencyAlternateKey\", type text}, {\"CurrencyName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_995069ca-15bd-4c6c-8211-0d8c80400119",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "68b5be6d-8084-4a8c-afb3-3ece96b720bc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "bf5e9a10-0510-4986-8eff-180d3dddb4ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2cca30e0-9583-4c2f-839b-d0d7fb2775a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "015ba720-c973-4571-8f6e-803fb3869c4d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b72290af-b413-4742-aa73-54c9f51e6654",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "41045194-452e-4e73-a0b7-f3f3b5ec6995",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0eb5acdd-af9e-4049-a38e-4b675038e7ef",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5a512aed-a8da-4df6-8b6b-f9e9a158e503",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e0af4f29-673b-42fa-941f-89ef502271fe",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "69b9d25a-33cb-40c2-a7dc-376c0435dc53",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "445d83bb-5511-4c3c-bed4-cca24d874426",
                "ordinal": 3
              }
            ],
            "lineageTag": "e00c96fb-e394-46d8-b5a9-cfca3f14e96e"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0f3f51e5-ecf8-4501-b138-d40912464eb8",
        "partitions": [
          {
            "name": "DateTableTemplate_995069ca-15bd-4c6c-8211-0d8c80400119",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3869a23b-6289-4ce6-82fc-a139d36f1c77",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50055b3a-d4f3-4422-91d8-45e078cff739",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c39e5199-c1d5-4dd8-b45c-e2a14a48d683",
            "sourceColumn": "CustomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7eafadd-bb2f-4499-9a00-e55c5b8134f5",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8453c7c3-a7a6-4305-b938-ff45b518d838",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4c544c6-501f-4cfc-8b96-b26b3ef9af0a",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abc0de3c-d8f6-4ff4-8a6b-b8524269b7e6",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "NameStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9728a22e-d67e-4955-b955-3991a0d881c2",
            "sourceColumn": "NameStyle",
            "summarizeBy": "sum"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f86237ac-8999-4018-92b5-dbfdd0e3402b",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_22d855fd-72d2-47d1-83d6-ea7b18773cdc"
                },
                "isDefault": true,
                "relationship": "25e17877-4dc6-4477-a1b6-7aac7a7521fb"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2beb949-b6c8-468e-b212-682dcaf9d6a3",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c5ed01e-4c22-4a7f-9477-22b3a1fcf8a4",
            "sourceColumn": "Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebc841b6-2719-49e6-b567-90cbaec1b558",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "363b1530-81aa-48ff-a19b-3699ceef2764",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "356e2d90-3441-4f87-9b68-7d12c94b1345",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5ac4e8c-6f73-47ff-926a-7074bd1b2ff4",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberChildrenAtHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c260e730-2076-4e9d-907b-68419b5f5f5b",
            "sourceColumn": "NumberChildrenAtHome",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00dd232a-cc9c-4921-a5d3-b270c01ceb55",
            "sourceColumn": "EnglishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fd85ec1-a62e-46a0-99f1-93d01fcb4e65",
            "sourceColumn": "SpanishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebf69668-ffd2-454c-918e-0492c41d867e",
            "sourceColumn": "FrenchEducation",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d13d6b84-fd01-4af0-8d4e-a89c2d04fc8f",
            "sourceColumn": "EnglishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e7e49e1-019a-42e8-87a0-d6f84e43a495",
            "sourceColumn": "SpanishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "662137ab-6397-41f4-97cc-5db30f4f5fa9",
            "sourceColumn": "FrenchOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34a4fbc8-f247-42b0-bbb0-232d01eb114d",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberCarsOwned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73e99d6d-fede-45e1-845c-a4cecf7ab9a7",
            "sourceColumn": "NumberCarsOwned",
            "summarizeBy": "sum"
          },
          {
            "name": "AddressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18ee5789-db14-4a9b-aca6-a1c558e9f278",
            "sourceColumn": "AddressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "AddressLine2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4903b0a3-d32c-4d6f-a165-ad610f0617f2",
            "sourceColumn": "AddressLine2",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e5f27ec-7730-4708-958b-11237cb0f788",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "DateFirstPurchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "06869b94-44c6-4e00-a65f-ca2c43fc1ced",
            "sourceColumn": "DateFirstPurchase",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8d6ff6fd-407c-4b21-b7b2-e2fa0ecb12cd"
                },
                "isDefault": true,
                "relationship": "afb763cb-5e25-436e-8758-2f1c93815b2f"
              }
            ]
          },
          {
            "name": "CommuteDistance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3da44b4b-9742-4edb-a64b-6a3dd500126a",
            "sourceColumn": "CommuteDistance",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "28a4b14c-ab68-439f-8bb6-335e35024fcb",
        "partitions": [
          {
            "name": "dim_Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\365 Data Science Power BI\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Customer_Sheet = Source{[Item=\"dim_Customer\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Customer_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"CustomerAlternateKey\", type text}, {\"Title\", type text}, {\"FirstName\", type text}, {\"MiddleName\", type text}, {\"LastName\", type text}, {\"NameStyle\", Int64.Type}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Suffix\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"YearlyIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"NumberChildrenAtHome\", Int64.Type}, {\"EnglishEducation\", type text}, {\"SpanishEducation\", type text}, {\"FrenchEducation\", type text}, {\"EnglishOccupation\", type text}, {\"SpanishOccupation\", type text}, {\"FrenchOccupation\", type text}, {\"HouseOwnerFlag\", Int64.Type}, {\"NumberCarsOwned\", Int64.Type}, {\"AddressLine1\", type text}, {\"AddressLine2\", type text}, {\"Phone\", type text}, {\"DateFirstPurchase\", type date}, {\"CommuteDistance\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_22d855fd-72d2-47d1-83d6-ea7b18773cdc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d51e6fab-752c-4dfb-b37c-fcc448287133",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d74d888b-9797-4d54-bd94-3a149f2797cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "201e86f3-4ec6-4daa-8e21-b36215e308e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5fcc82f2-cda0-48b7-895b-d07a53a86589",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "56b43e76-c6d9-4780-ae67-1e1c1f8a5293",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "247917c0-9229-4d58-b09e-eca849a0185a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9b61d0f9-8199-4cc6-833f-4600c2524272",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "179e94c6-19e4-4614-b46b-e3809ae76d74",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9f33576c-45ca-4b7d-a764-d77a11dfab51",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "91ca302c-a546-410d-a2b5-c1cdf9f56677",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "902ec758-b0fb-43c2-afec-4a25d755bf3f",
                "ordinal": 3
              }
            ],
            "lineageTag": "dc959f08-f20c-4a0a-ade3-58935faf1337"
          }
        ],
        "isHidden": true,
        "lineageTag": "f9bcdfe9-4143-4183-9335-9fb62e8bb991",
        "partitions": [
          {
            "name": "LocalDateTable_22d855fd-72d2-47d1-83d6-ea7b18773cdc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[BirthDate])), 1, 1), Date(Year(MAX('dim_Customer'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8d6ff6fd-407c-4b21-b7b2-e2fa0ecb12cd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "494fb9ef-605e-4e04-9630-253a78fb4a54",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0a314c72-493a-406a-adb5-35859598285c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "365c80ce-7f05-4800-8e93-f6ca7c03401f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d5253aff-f2b6-4651-aaec-f03e964b2356",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "71663519-3c45-4ec7-90ca-d38a8fc16eb5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "82bc7a18-85fd-48ff-8da6-ac881b9fac1c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d5c6fe19-46f2-4195-8cb5-a1f223652851",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "881e7cc6-795c-4759-a0dc-f15579dd36f9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "39030dd7-828a-4a1c-b645-dc69fba870d8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "24832942-d44b-40ab-b6ba-da639b14e4dd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c4eade59-c58c-4973-b474-13da4f890793",
                "ordinal": 3
              }
            ],
            "lineageTag": "5675dd47-5a71-4eec-ae16-100109489541"
          }
        ],
        "isHidden": true,
        "lineageTag": "318c6672-1ec0-494f-bc54-18cf7a0da243",
        "partitions": [
          {
            "name": "LocalDateTable_8d6ff6fd-407c-4b21-b7b2-e2fa0ecb12cd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[DateFirstPurchase])), 1, 1), Date(Year(MAX('dim_Customer'[DateFirstPurchase])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_SalesTerritory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f1412835-e592-40b6-abe3-deda8a2334ab",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b768d71f-15a7-4a1f-a186-ecfc6746d39c",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35a1c753-0e17-4741-9edd-18ea66fa276d",
            "sourceColumn": "SalesTerritoryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "485e8e15-b598-4b71-a244-ce2408a194e2",
            "sourceColumn": "SalesTerritoryCountry",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec81b188-2df7-4dce-a479-d28a02f3ca53",
            "sourceColumn": "SalesTerritoryGroup",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68db499e-6d19-4811-8a39-ca8e1144b78a",
        "partitions": [
          {
            "name": "dim_SalesTerritory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\365 Data Science Power BI\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_SalesTerritory_Sheet = Source{[Item=\"dim_SalesTerritory\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_SalesTerritory_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"SalesTerritoryAlternateKey\", Int64.Type}, {\"SalesTerritoryRegion\", type text}, {\"SalesTerritoryCountry\", type text}, {\"SalesTerritoryGroup\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_InternetSales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a45f344-4cda-4219-a718-6a81171ada12",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ce0856e-e38a-4b7d-986c-3d288eee467f",
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f68ce2d7-3e5b-43be-8d8f-7b44c0bb76a7",
            "sourceColumn": "DueDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1cc6e64d-30cf-4b5e-9a26-b902f4450e25",
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7738fbd-877c-471c-93bc-dc9f19177612",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91178822-aaf0-4692-b4f2-b5f2820e3075",
            "sourceColumn": "PromotionKey",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cdfcc18a-dffd-43bc-a313-9d5fbbbdd918",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97aa2f28-2a28-467c-8fde-1f79de343ae2",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0a94e9e-bbd8-46e5-b18f-309c25fee469",
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f6deefc-8120-4054-a306-fa6103a48470",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c853c170-5006-44aa-ba8d-d05aff3e5341",
            "sourceColumn": "RevisionNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a617e6d3-2927-4a19-941b-4018d5095ec1",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "150871d2-ce32-480a-a228-d14112c4d129",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54dd37a5-7a4c-45a1-9552-8b2d04522baa",
            "sourceColumn": "ExtendedAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e6c4805-0527-459e-95d1-a42b2ea382ab",
            "sourceColumn": "UnitPriceDiscountPct",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d4f40a7-f963-4c35-86a0-b2a568046c4e",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcbbeab2-62ec-4946-bbbc-f38e8ebc3737",
            "sourceColumn": "ProductStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7823d704-6f2a-4d9e-9e01-f3dd8c14cde9",
            "sourceColumn": "TotalProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "62ecd9ec-75aa-4c19-9f3f-7bf5a6959c2d",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b71eff8-3f6f-4644-a5a1-5c7e56d35622",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "18eb22b5-b238-415d-9122-3d3da2dbfae0",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "CarrierTrackingNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "776664d8-7160-4b24-8eba-737e32a58515",
            "sourceColumn": "CarrierTrackingNumber",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerPONumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ed7cda3-7c1d-4f11-b545-757a46025423",
            "sourceColumn": "CustomerPONumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1f3c5173-d07b-4c25-b685-eed275bc1235",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_734177d9-7e0e-49b7-92ab-36014931130a"
                },
                "isDefault": true,
                "relationship": "05d3c491-d361-4c6f-872d-557738746fa6"
              }
            ]
          },
          {
            "name": "DueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "dec1665f-dc44-47db-9993-66381327c14f",
            "sourceColumn": "DueDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3364ad5d-e938-4ce4-b154-5dc0cc8fc6d8"
                },
                "isDefault": true,
                "relationship": "5ee69d2e-e4b1-40f4-9c9a-ba8007210467"
              }
            ]
          },
          {
            "name": "ShipDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a1b8a29a-8b72-4922-852c-27ee4c5be65c",
            "sourceColumn": "ShipDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3d26bdf8-f479-4972-b8e9-407ae491cb95"
                },
                "isDefault": true,
                "relationship": "1d1c9870-7f5f-45fd-a0b4-d3ff6421935f"
              }
            ]
          }
        ],
        "lineageTag": "6a1f0ee2-b42f-4651-9f67-23b1a2a19511",
        "partitions": [
          {
            "name": "fact_InternetSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\365 Data Science Power BI\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    fact_InternetSales_Sheet = Source{[Item=\"fact_InternetSales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(fact_InternetSales_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"OrderDateKey\", Int64.Type}, {\"DueDateKey\", Int64.Type}, {\"ShipDateKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"PromotionKey\", Int64.Type}, {\"CurrencyKey\", Int64.Type}, {\"SalesTerritoryKey\", Int64.Type}, {\"SalesOrderNumber\", type text}, {\"SalesOrderLineNumber\", Int64.Type}, {\"RevisionNumber\", Int64.Type}, {\"OrderQuantity\", Int64.Type}, {\"UnitPrice\", type number}, {\"ExtendedAmount\", type number}, {\"UnitPriceDiscountPct\", Int64.Type}, {\"DiscountAmount\", Int64.Type}, {\"ProductStandardCost\", type number}, {\"TotalProductCost\", type number}, {\"SalesAmount\", type number}, {\"TaxAmt\", type number}, {\"Freight\", type number}, {\"CarrierTrackingNumber\", type text}, {\"CustomerPONumber\", type text}, {\"OrderDate\", type datetime}, {\"DueDate\", type datetime}, {\"ShipDate\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_734177d9-7e0e-49b7-92ab-36014931130a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d435c068-4f56-4d10-9d48-6bb4afcaabf5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0d60019d-e0da-416c-8597-474f862ea7ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "846d9f9a-2508-4820-ba6e-7bf1d824a0b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d1febc40-62b8-44ec-b3b6-a04c2093ca0c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "69c3df32-acc1-4752-bf17-cdc1e95b199b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5c883294-dad0-4a25-b7b4-a7a9dfd922c3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3269379b-5672-4a49-8643-e5de43808ed4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f23bc639-f39f-4f43-b94d-fab2e0f87ba4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d7a34fdd-902e-4b14-978b-8a77ddb4f1fd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "09b7adb4-acd8-4e17-a860-57326f9feae1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6a7cd77d-16c6-444e-a3f5-8bd88adfb561",
                "ordinal": 3
              }
            ],
            "lineageTag": "452bd7c9-5b1f-4238-ade6-f1cd882a0212"
          }
        ],
        "isHidden": true,
        "lineageTag": "874c5fb6-2306-4e87-91ac-052eb4bead1e",
        "partitions": [
          {
            "name": "LocalDateTable_734177d9-7e0e-49b7-92ab-36014931130a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[OrderDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3364ad5d-e938-4ce4-b154-5dc0cc8fc6d8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d8fc67d2-32f0-44f1-b3d1-8ab594bc970d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2f670ee8-b42c-47b3-bfe3-b956dc675936",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "03ae862f-9600-4f1c-a763-7144295ef8fb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6915dab1-5dd1-4ede-82cf-8d525c60ed0a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5913420d-12db-4dab-85da-3889726b0c07",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0de37dca-7e6e-49c2-adbf-8940a8b43567",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "024b3bc6-8ed7-4f9a-94ee-934fd6aea3c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ab10d17f-3014-448c-a7ab-4e82bfe459ba",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4632bdbe-553e-4af2-93dd-4698ae3535c1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "07c9e006-c806-4cb4-9057-c543ab66a13b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0ff7135d-d4f0-47dc-84b5-5539d5edfd5d",
                "ordinal": 3
              }
            ],
            "lineageTag": "d2bdb584-acba-4904-978b-27096a71cc88"
          }
        ],
        "isHidden": true,
        "lineageTag": "9fcdd521-2715-47ea-9a8e-bf55e6883be8",
        "partitions": [
          {
            "name": "LocalDateTable_3364ad5d-e938-4ce4-b154-5dc0cc8fc6d8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[DueDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[DueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3d26bdf8-f479-4972-b8e9-407ae491cb95",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c25e6860-9ce0-4f92-80d9-1c8dfdd994e8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cee1c449-a366-4705-b6f6-ff591f1f6b20",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "44d4d956-449f-436b-94ea-d5ffd40a18ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7f4a43e9-91fd-466d-9f2e-acf9fd5d8a75",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "54d2d4cb-e207-4fcf-9ed8-d2b594a69e24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fab0100c-5989-4197-9fc8-38af01d02c17",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b6f889c1-c5c8-43af-97fd-3a36d61ce666",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "74632ff5-5c52-4331-9d7a-16bd03b7c6e9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8b29ad24-8501-4821-9b2c-d3d0b5864ac2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ddb7ae9e-a277-419c-9bcb-6c0af907b094",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f8ff4b75-8226-4781-808c-0adcaef58523",
                "ordinal": 3
              }
            ],
            "lineageTag": "90359aad-47b6-4c2f-9294-313593ea7cf5"
          }
        ],
        "isHidden": true,
        "lineageTag": "c2a5d154-2f32-42d6-bd54-f7c660cd7da0",
        "partitions": [
          {
            "name": "LocalDateTable_3d26bdf8-f479-4972-b8e9-407ae491cb95",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[ShipDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[ShipDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de15399c-daaf-4c0b-9994-6f477389892c",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db19ab15-e1c4-41a7-b54f-657781bac971",
            "sourceColumn": "EnglishProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "764659db-a0d6-4994-a24d-e33d44afc4f3",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f00d40da-e66c-483a-a1e1-c646fa826191",
        "partitions": [
          {
            "name": "dim_Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\365 Data Science Power BI\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Product_Sheet = Source{[Item=\"dim_Product\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Product_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"EnglishProductName\", type text}, {\"Color\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "#Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "289b33b6bfba4067b8e404287f3c17c8"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7af9a555-e950-40e4-8373-c28d6f0c743a",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c10ed324-c8db-411a-8c92-4490c0dd94b8",
        "measures": [
          {
            "name": "ProductsSold",
            "expression": "COUNTROWS(fact_InternetSales)",
            "formatString": "0",
            "lineageTag": "a4680089-d5d9-4ee9-8124-fa437067b3a7"
          },
          {
            "name": "Customers",
            "expression": "COUNTROWS(dim_Customer)",
            "formatString": "0",
            "lineageTag": "6a00f73b-eb15-40b8-b5cd-3dec62c70ff3"
          },
          {
            "name": "TotalSalesAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(fact_InternetSales[SalesAmount])",
            "lineageTag": "1cf1fde4-9ac4-4fab-9b64-b42a15393881"
          }
        ],
        "partitions": [
          {
            "name": "#Measures",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1,1,1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}