{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"twitch dataset\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.1229.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "twitch dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RANK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4aa5f55-2328-4359-8337-5ec7461cc91a",
            "sourceColumn": "RANK",
            "summarizeBy": "sum"
          },
          {
            "name": "NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96a1041d-c0b7-4a42-8eeb-71c906584ae8",
            "sourceColumn": "NAME",
            "summarizeBy": "none"
          },
          {
            "name": "LANGUAGE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5652be3-85ae-46dc-9c09-6eedf9f5a193",
            "sourceColumn": "LANGUAGE",
            "summarizeBy": "none"
          },
          {
            "name": "TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aa91934-062b-421b-899c-6ce0d3ecb004",
            "sourceColumn": "TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "MOST_STREAMED_GAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b82bf98c-225b-495d-8623-1000bf59008d",
            "sourceColumn": "MOST_STREAMED_GAME",
            "summarizeBy": "none"
          },
          {
            "name": "2ND_MOST_STREAMED_GAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "925bcb24-043b-46bd-91be-4be56c55da31",
            "sourceColumn": "2ND_MOST_STREAMED_GAME",
            "summarizeBy": "none"
          },
          {
            "name": "AVERAGE_STREAM_DURATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "131d8889-52d7-424f-aa46-739b687c4bae",
            "sourceColumn": "AVERAGE_STREAM_DURATION",
            "summarizeBy": "sum"
          },
          {
            "name": "FOLLOWERS_GAINED_PER_STREAM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "a450b902-3570-4476-b79e-a1fab4b36eac",
            "sourceColumn": "FOLLOWERS_GAINED_PER_STREAM",
            "summarizeBy": "sum"
          },
          {
            "name": "AVG_VIEWERS_PER_STREAM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "1d56f9e0-d68a-4f73-9c69-b336e988f2c0",
            "sourceColumn": "AVG_VIEWERS_PER_STREAM",
            "summarizeBy": "sum"
          },
          {
            "name": "AVG_GAMES_PER_STREAM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "df852ef8-acbe-4848-a10d-725faa210518",
            "sourceColumn": "AVG_GAMES_PER_STREAM",
            "summarizeBy": "sum"
          },
          {
            "name": "TOTAL_TIME_STREAMED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcccab54-229f-47bb-b596-d6018ece74ff",
            "sourceColumn": "TOTAL_TIME_STREAMED",
            "summarizeBy": "sum"
          },
          {
            "name": "TOTAL_FOLLOWERS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52e51fc0-daed-4aa2-8be7-87351a9e39ad",
            "sourceColumn": "TOTAL_FOLLOWERS",
            "summarizeBy": "sum"
          },
          {
            "name": "TOTAL_VIEWS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "573a14c2-12b6-470d-9368-c425b213fd3d",
            "sourceColumn": "TOTAL_VIEWS",
            "summarizeBy": "sum"
          },
          {
            "name": "TOTAL_GAMES_STREAMED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "622eaaff-68cd-4d58-ab89-5ce89e6a173c",
            "sourceColumn": "TOTAL_GAMES_STREAMED",
            "summarizeBy": "sum"
          },
          {
            "name": "ACTIVE_DAYS_PER_WEEK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e1e23b7-f1f3-475c-b889-a94ec342fa06",
            "sourceColumn": "ACTIVE_DAYS_PER_WEEK",
            "summarizeBy": "sum"
          },
          {
            "name": "MOST_ACTIVE_DAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "500cd275-4c4d-4c0e-9822-7c76833aeaf1",
            "sourceColumn": "MOST_ACTIVE_DAY",
            "summarizeBy": "none"
          },
          {
            "name": "DAY_WITH_MOST_FOLLOWERS_GAINED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f8dba32-a85b-414c-94ee-e1ecd6b3c459",
            "sourceColumn": "DAY_WITH_MOST_FOLLOWERS_GAINED",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f5d5743b-beca-414e-9c21-19297d780824",
        "partitions": [
          {
            "name": "twitch dataset",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Damyan\\Desktop\\Work Docs\\Power BI\\Twitch Streamers Dashboard\\twitch dataset.csv\"),[Delimiter=\",\", Columns=17, Encoding=1251, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"RANK\", Int64.Type}, {\"NAME\", type text}, {\"LANGUAGE\", type text}, {\"TYPE\", type text}, {\"MOST_STREAMED_GAME\", type text}, {\"2ND_MOST_STREAMED_GAME\", type text}, {\"AVERAGE_STREAM_DURATION\", type text}, {\"FOLLOWERS_GAINED_PER_STREAM\", type text}, {\"AVG_VIEWERS_PER_STREAM\", type text}, {\"AVG_GAMES_PER_STREAM\", type text}, {\"TOTAL_TIME_STREAMED\", type text}, {\"TOTAL_FOLLOWERS\", Int64.Type}, {\"TOTAL_VIEWS\", Int64.Type}, {\"TOTAL_GAMES_STREAMED\", Int64.Type}, {\"ACTIVE_DAYS_PER_WEEK\", type text}, {\"MOST_ACTIVE_DAY\", type text}, {\"DAY_WITH_MOST_FOLLOWERS_GAINED\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_da552849-27b8-4350-9964-278cfd28b87f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b7afaf55-4f2e-4df1-8b40-d31febf6efbc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eabfc852-6a37-4131-82e1-c92bccedd0d4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6c2d89eb-142e-487d-99e1-deaa00539a3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "18e4f46c-e9f9-4de2-b872-9f28e964d81d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b353912a-2377-40a2-b33d-b8c50c1212e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "611859c1-0d8a-4124-858e-0ce01a705d07",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8b6e0cd-a225-4d7f-acd8-eb2733266274",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2c76f702-f777-4acd-9149-ab114ff8dfdb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c84d1fdd-f024-4f34-8fbf-7eebf1672e22",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d38cd3fc-d6a8-478c-82ec-5e0224662f4d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fefb122a-f513-4dca-aed3-be92ee2bbfc0",
                "ordinal": 3
              }
            ],
            "lineageTag": "d1c066f4-4104-45d8-b8b8-4b3ab9d3aae6"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3eae327a-3b2e-4119-8f28-fe88d839baaa",
        "partitions": [
          {
            "name": "DateTableTemplate_da552849-27b8-4350-9964-278cfd28b87f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}