{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Call Center_Call Center\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "67159553-cec7-4723-b10b-fa31933e9730",
        "fromColumn": "Date",
        "fromTable": "Date Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e46b2535-1f21-43be-ba89-d4bfefb3f08f"
      },
      {
        "name": "0b44b7e4-677b-4585-aa4d-4e11e546909a",
        "fromColumn": "Call Timestamp",
        "fromTable": "Call Center_Call Center",
        "toColumn": "Date",
        "toTable": "Date Table"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "Call Center_Call Center",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25ce3bb1-3e90-4b90-a8b3-a2f6bf17cfed",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Call Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cdc3ce84-812a-4de0-bb8a-889c157fdc5e",
            "sourceColumn": "Call Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Call-Centres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c784583-862b-4670-a35b-11a3217730fc",
            "sourceColumn": "Call-Centres",
            "summarizeBy": "none"
          },
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddbf8f0e-4af9-463a-9d01-728e268f94fd",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1fa3b6d-f475-49c7-b11e-0ef35c079a4d",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "055a54a2-fa53-426d-8f91-d2b5affb47d1",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aff54307-5820-4d91-a9c7-1b3c97416a70",
            "sourceColumn": "Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Response Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51355413-772b-438b-aedf-23717d75cf04",
            "sourceColumn": "Response Time",
            "summarizeBy": "none"
          },
          {
            "name": "Sentiment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c69ac7b-4091-41ef-92a2-117e9caa386c",
            "sourceColumn": "Sentiment",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5e498ee-4330-40ad-a42d-e87c7f69f9cf",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Call Duration In Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e7eb8d9d-ddcc-47dd-a924-40a54d9646b7",
            "sourceColumn": "Call Duration In Minutes",
            "summarizeBy": "sum"
          },
          {
            "name": "Csat Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79828c43-6e09-43c2-9e76-02527de60d97",
            "sourceColumn": "Csat Score",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "16c21911-1ac3-405f-96a6-2e42de319209",
        "measures": [
          {
            "name": "Total Calls",
            "expression": "COUNT('Call Center_Call Center'[Id])",
            "formatString": "0.00",
            "lineageTag": "ac4e270e-47dc-457f-bdb6-1eed27eeef81"
          },
          {
            "name": "Total Call Duration (min)",
            "expression": "SUM('Call Center_Call Center'[Call Duration In Minutes])",
            "formatString": "0.00",
            "lineageTag": "38b06fdf-b63c-4d77-9870-0783dd4ba56c"
          },
          {
            "name": "Total Call Duration (hrs)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Call Duration (min)] / 60",
            "lineageTag": "ff44f181-ea41-473c-80ef-d029fd8181b5"
          },
          {
            "name": "Avg Call Duration (min)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('Call Center_Call Center'[Call Duration In Minutes])",
            "lineageTag": "1f41ae03-f82d-4b20-a4a0-dffd294e35c9"
          },
          {
            "name": "Response Time %",
            "expression": "CALCULATE([Total Calls], 'Call Center_Call Center'[Response Time] = \"Within SLA\" || 'Call Center_Call Center'[Response Time] = \"Above SLA\") / [Total Calls]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "882f193b-c987-475c-a19a-5b17349a0828"
          }
        ],
        "partitions": [
          {
            "name": "Call Center_Call Center",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Damyan\\Desktop\\Call Center_Call Center.csv\"),[Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Id\", type text}, {\"Call Timestamp\", type date}, {\"Call-Centres City\", type text}, {\"Channel\", type text}, {\"City\", type text}, {\"Customer Name\", type text}, {\"Reason\", type text}, {\"Response Time\", type text}, {\"Sentiment\", type text}, {\"State\", type text}, {\"Call Duration In Minutes\", Int64.Type}, {\"Csat Score\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Call-Centres City\", \"Call-Centres\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_b827ec7d-063e-44a2-9fa5-3ad30d52f14d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e70f227d-c2f1-4a06-8fb5-a1b2c92cd850",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "52a6d4a2-8f1c-4643-b95e-9d285d748d19",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6cad3d99-77c6-42a4-b6b8-f55a04e655f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0bd9c351-3a94-4600-b225-04c525ec4557",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a559aa4a-ead4-4225-aa6c-f34d64e2aabb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "deb18741-6f9e-44dd-8bad-4433896df4e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2c1218e6-9065-4a5d-9cf6-3d09dfb89e26",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c4c108cb-7a99-4f9f-8a6c-bd0ba3141203",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b820a4a9-63ef-400d-adb1-c9b34b053649",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "98a6ebef-1e87-45cd-b8ee-1703abaebe01",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "793c6e8d-7eb6-4ec4-aea6-f95b4e77722b",
                "ordinal": 3
              }
            ],
            "lineageTag": "44dd6e3e-0bd7-4272-9843-899a258c7eb7"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "933093b5-838c-4a33-b09a-3d28930c30a4",
        "partitions": [
          {
            "name": "DateTableTemplate_b827ec7d-063e-44a2-9fa5-3ad30d52f14d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "faf96dc602814bcfa528fc3be4a9ccf6"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "66e215cf-23b8-4eb7-9aea-73909807b6e4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e46b2535-1f21-43be-ba89-d4bfefb3f08f"
                },
                "isDefault": true,
                "relationship": "67159553-cec7-4723-b10b-fa31933e9730"
              }
            ]
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Date Table'[Date], \"ddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "3f2a2404-2dda-41ff-987d-08939fc8a2e9",
            "sortByColumn": "Day Number",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY('Date Table'[Date], 2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a99bf5a5-dddb-49cf-8129-c176132005bb",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "e4200995-5114-4378-9465-1fbfc7b58a69",
        "partitions": [
          {
            "name": "Date Table",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN('Call Center_Call Center'[Call Timestamp]), MAX('Call Center_Call Center'[Call Timestamp]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e46b2535-1f21-43be-ba89-d4bfefb3f08f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c3a25eaa-dffc-45c3-9a3a-e7c9bf81484a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "352b4b65-581b-49e4-b913-771a08a8e390",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f074cc76-8e42-4964-9793-e74f84bd7abf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8f87b0ea-29c3-4406-ba41-3d62f763bc43",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "73169408-4b1f-4e1a-b7dc-cbcf1003c7be",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "88b5f5e9-0b5f-41b5-98e6-79094dea4ba4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ae6573a2-453b-4a9d-8d4f-434cc55cc934",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9793e2dc-5bdf-49ea-a225-b25048df7f58",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d837b79f-53e0-4582-b85f-1b01c2bef1c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ddb0ee28-21ec-4ec9-b2ee-8608f6f9ff3d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "78f29beb-887d-4dcf-b9eb-85af962dc75c",
                "ordinal": 3
              }
            ],
            "lineageTag": "f7da132c-ad54-466a-813e-8e634aac7af4"
          }
        ],
        "isHidden": true,
        "lineageTag": "b965b4fe-acf3-4caf-931f-4af3907607b6",
        "partitions": [
          {
            "name": "LocalDateTable_e46b2535-1f21-43be-ba89-d4bfefb3f08f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date Table'[Date])), 1, 1), Date(Year(MAX('Date Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}