{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"ASIN\",\"Sales Data\",\"Metrics\",\"inventory\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.901.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "asin": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "ASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asin": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "asin.SKU_amazon": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "ASIN",
                    "ConceptualProperty": "SKU (Amazon)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "SKU (amazon)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "SKU": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "asin.asin": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "ASIN",
                    "ConceptualProperty": "ASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asin": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "inventory": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "inventory"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "inventory": {
                      "State": "Generated"
                    }
                  },
                  {
                    "portfolio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "account": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "register": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "catalogue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "catalog": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "roster": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "stock": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "array": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "inventory.TOTAL_INVENTORY_unit": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "inventory",
                    "ConceptualProperty": "TOTAL INVENTORY Units"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "TOTAL INVENTORY unit": {
                      "State": "Generated"
                    }
                  },
                  {
                    "unit": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "INVENTORY unit": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "total inventory module": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total inventory element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total inventory entity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "inventory module": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "inventory element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "inventory entity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total inventory group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory component": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory constituent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "Inventory Units": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "inventory.asin": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "inventory",
                    "ConceptualProperty": "ASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asin": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "metrics": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "metrics": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "metrics.total_earnings": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "Total Earnings"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total earnings": {
                      "State": "Generated"
                    }
                  },
                  {
                    "earnings": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate earnings": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall earnings": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total salary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total paycheck": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total remuneration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total retribution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "salary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "paycheck": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "metrics.total_products_inventory": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "Total Inventory Products"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total inventory products": {
                      "State": "Generated"
                    }
                  },
                  {
                    "products": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "inventory products": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "total inventory artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "inventory artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total inventory item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "inventory item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "inventory merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "inventory produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "metrics.total_products_sold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "Total Products Sold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total products sold": {
                      "State": "Generated"
                    }
                  },
                  {
                    "total artifact sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total item sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total merchandise sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total produce sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total goods sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.635
                    }
                  },
                  {
                    "aggregate product sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "overall product sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  }
                ]
              },
              "sales_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sales data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale data": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "data": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "sale fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "sale info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "sale statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "sale document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "sale figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "sales_data.amazonorderid": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "amazon-order-id"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "amazon-order-id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "amazon order id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "amazon order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "amazon-order-identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon-order-identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon-order-identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon order identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon order identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon order identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon-order-credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "order identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "sales_data.buyeremail": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "buyer-email"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "buyer-email": {
                      "State": "Generated"
                    }
                  },
                  {
                    "buyer email": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "email": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "buyer-correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "buyer correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "buyer-message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.468
                    }
                  },
                  {
                    "buyer-communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.468
                    }
                  },
                  {
                    "buyer message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "buyer communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "sales_data.carrier": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "carrier"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "carrier": {
                      "State": "Generated"
                    }
                  },
                  {
                    "transporter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "hauler": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "carter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "shipper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "mover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "exporter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "importer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "transferor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "sales_data.currency": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "currency"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "currency": {
                      "State": "Generated"
                    }
                  },
                  {
                    "money": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "coinage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "exchange": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "prevalence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "popularity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "vogue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "circulation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "commonness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "sales_data.itemprice": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "item-price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "item-price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "item price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "element -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "entry -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "product price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "element price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "entry price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "article -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "object -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "piece -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "token -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  }
                ]
              },
              "sales_data.itempromotiondiscount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "item-promotion-discount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "item-promotion-discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "item promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "element -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "entry -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "product promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "element promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "entry promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "article -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "object -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "piece -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "token -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  }
                ]
              },
              "sales_data.purchasedate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase-date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "purchase date": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "purchase-period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "purchase period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "sales_data.purchasedate.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "sales_data.purchasedate.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "purchase period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "sales_data.purchasedate.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase - mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchase-moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "sales_data.purchasedate.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.857
                    }
                  },
                  {
                    "purchase - qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "purchase date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "purchase qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "purchase-moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "sales_data.purchasedate.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase - yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchase-moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "sales_data.quantityshipped": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "quantity-shipped"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantity-shipped": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quantity shipped": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "extent shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "magnitude shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "amount shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "number shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "measure shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "size shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "capacity shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "mass shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "sales_data.saleschannel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "sales-channel"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sales-channel": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale-channel": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "sales channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale channel": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7566
                    }
                  },
                  {
                    "channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale -channel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "sale-frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "sale frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "sale-station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "sale-network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "sale station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale-conduit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  }
                ]
              },
              "sales_data.shipcountry": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "ship-country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "ship location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "sales_data.shippostalcode": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "ship-postal-code"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-postal-code": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship postal code": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-postal-id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship postal id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-postal-key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship postal key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "sales_data.shippromotiondiscount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "ship-promotion-discount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-promotion-discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-promotion-reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship promotion reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship-promotion-rebate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.504
                    }
                  },
                  {
                    "promotion reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  }
                ]
              },
              "sales_data.shipservicelevel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "ship-service-level"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-service-level": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship service level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "service level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-service-quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship-service-threshold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship service quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship service threshold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-service-amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-grade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-tier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "service quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "sales_data.sku": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Sales Data",
                    "ConceptualProperty": "sku"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sku": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Product": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              }
            },
            "Language": "en-US",
            "Relationships": {
              "asin_has_SKU_amazon": {
                "Binding": {
                  "ConceptualEntity": "ASIN"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asin.SKU_amazon"
                      },
                      "Subject": {
                        "Role": "asin"
                      }
                    },
                    "ID": "asins_have_SKU_amazon",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asin": {
                    "Target": {
                      "Entity": "asin"
                    }
                  },
                  "asin.SKU_amazon": {
                    "Target": {
                      "Entity": "asin.SKU_amazon"
                    }
                  }
                },
                "State": "Generated"
              },
              "asin_has_inventory": {
                "Binding": {
                  "ConceptualEntity": "ASIN"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "inventory"
                      },
                      "Subject": {
                        "Role": "asin"
                      }
                    },
                    "ID": "asins_have_inventories",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asin"
                      },
                      "Subject": {
                        "Role": "inventory"
                      }
                    },
                    "ID": "inventories_have_asins",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asin": {
                    "Target": {
                      "Entity": "asin"
                    }
                  },
                  "inventory": {
                    "Target": {
                      "Entity": "inventory"
                    }
                  }
                },
                "State": "Generated"
              },
              "inventory_has_TOTAL_INVENTORY_unit": {
                "Binding": {
                  "ConceptualEntity": "inventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "inventory.TOTAL_INVENTORY_unit"
                      },
                      "Subject": {
                        "Role": "inventory"
                      }
                    },
                    "ID": "inventories_have_TOTAL_INVENTORY_units",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "inventory": {
                    "Target": {
                      "Entity": "inventory"
                    }
                  },
                  "inventory.TOTAL_INVENTORY_unit": {
                    "Target": {
                      "Entity": "inventory.TOTAL_INVENTORY_unit"
                    }
                  }
                },
                "State": "Generated"
              },
              "inventory_has_asin": {
                "Binding": {
                  "ConceptualEntity": "inventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "inventory.asin"
                      },
                      "Subject": {
                        "Role": "inventory"
                      }
                    },
                    "ID": "inventories_have_asins1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "inventory": {
                    "Target": {
                      "Entity": "inventory"
                    }
                  },
                  "inventory.asin": {
                    "Target": {
                      "Entity": "inventory.asin"
                    }
                  }
                },
                "State": "Generated"
              },
              "inventory_has_metrics_total_products_inventory": {
                "Binding": {
                  "ConceptualEntity": "inventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.total_products_inventory"
                      },
                      "Subject": {
                        "Role": "inventory"
                      }
                    },
                    "ID": "inventories_have_total_inventory_products",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "inventory": {
                    "Target": {
                      "Entity": "inventory"
                    }
                  },
                  "metrics.total_products_inventory": {
                    "Target": {
                      "Entity": "metrics.total_products_inventory"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_amazonorderid": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.amazonorderid"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_amazonorderids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.amazonorderid": {
                    "Target": {
                      "Entity": "sales_data.amazonorderid"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_asin": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asin"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_asins",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data"
                      },
                      "Subject": {
                        "Role": "asin"
                      }
                    },
                    "ID": "asins_have_sales_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asin": {
                    "Nouns": [
                      {
                        "sku": {
                          "State": "Generated"
                        }
                      },
                      {
                        "Product": {
                          "State": "Generated"
                        }
                      }
                    ],
                    "Target": {
                      "Entity": "asin"
                    }
                  },
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_buyeremail": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.buyeremail"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_buyeremails",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.buyeremail": {
                    "Target": {
                      "Entity": "sales_data.buyeremail"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_carrier": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.carrier"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_carriers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "carriers_carry_sales_data",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "sales_data"
                      },
                      "Subject": {
                        "Role": "sales_data.carrier"
                      },
                      "Verbs": [
                        {
                          "carry": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.75
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data"
                      },
                      "Subject": {
                        "Role": "sales_data.carrier"
                      }
                    },
                    "ID": "carriers_have_sales_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.carrier": {
                    "Target": {
                      "Entity": "sales_data.carrier"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_currency": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.currency"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_currencies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.currency": {
                    "Target": {
                      "Entity": "sales_data.currency"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_itemprice": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.itemprice"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_itemprices",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "sales_data.itemprice"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "itemprice_indicates_how_expensive_sales_data_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.itemprice": {
                    "Target": {
                      "Entity": "sales_data.itemprice"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_itempromotiondiscount": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.itempromotiondiscount"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_itempromotiondiscounts",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "sales_data.itempromotiondiscount"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "itempromotiondiscount_indicates_how_expensive_sales_data_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.itempromotiondiscount": {
                    "Target": {
                      "Entity": "sales_data.itempromotiondiscount"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_metrics_total_earnings": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.total_earnings"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_total_earnings",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics.total_earnings": {
                    "Target": {
                      "Entity": "metrics.total_earnings"
                    }
                  },
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_metrics_total_products_sold": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.total_products_sold"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_total_products_sold",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics.total_products_sold": {
                    "Target": {
                      "Entity": "metrics.total_products_sold"
                    }
                  },
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_purchasedate": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_purchasedates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.purchasedate": {
                    "Target": {
                      "Entity": "sales_data.purchasedate"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_quantityshipped": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.quantityshipped"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_quantityshipped",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.quantityshipped": {
                    "Target": {
                      "Entity": "sales_data.quantityshipped"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_saleschannel": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.saleschannel"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_saleschannels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.saleschannel": {
                    "Target": {
                      "Entity": "sales_data.saleschannel"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_shipcountry": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.shipcountry"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_shipcountries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shipcountry": {
                    "Target": {
                      "Entity": "sales_data.shipcountry"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_shippostalcode": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.shippostalcode"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_shippostalcodes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shippostalcode": {
                    "Target": {
                      "Entity": "sales_data.shippostalcode"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_shippromotiondiscount": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.shippromotiondiscount"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_shippromotiondiscounts",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "sales_data.shippromotiondiscount"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "shippromotiondiscount_indicates_how_expensive_sales_data_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shippromotiondiscount": {
                    "Target": {
                      "Entity": "sales_data.shippromotiondiscount"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_has_shipservicelevel": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.shipservicelevel"
                      },
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "ID": "sales_data_have_shipservicelevels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shipservicelevel": {
                    "Target": {
                      "Entity": "sales_data.shipservicelevel"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_in_shipcountry": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "ID": "sales_data_are_in_shipcountries",
                    "Preposition": {
                      "Object": {
                        "Role": "sales_data.shipcountry"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shipcountry": {
                    "Target": {
                      "Entity": "sales_data.shipcountry"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "sales_data.shipcountry"
                  }
                },
                "State": "Generated"
              },
              "sales_data_in_shippostalcode": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "ID": "sales_data_are_in_shippostalcodes",
                    "Preposition": {
                      "Object": {
                        "Role": "sales_data.shippostalcode"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "sales_data"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.shippostalcode": {
                    "Target": {
                      "Entity": "sales_data.shippostalcode"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "sales_data.shippostalcode"
                  }
                },
                "State": "Generated"
              },
              "sales_data_is_purchased_on_purchasedate": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "ID": "sales_data_are_purchased_on_purchasedates",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "sales_data"
                      },
                      "Verbs": [
                        {
                          "purchase": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.9
                  }
                ],
                "Roles": {
                  "sales_data": {
                    "Target": {
                      "Entity": "sales_data"
                    }
                  },
                  "sales_data.purchasedate": {
                    "Target": {
                      "Entity": "sales_data.purchasedate"
                    }
                  }
                },
                "SemanticSlots": {
                  "When": {
                    "Role": "sales_data.purchasedate"
                  }
                },
                "State": "Generated"
              },
              "sales_data_purchasedate_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "sales_data.purchasedate"
                      }
                    },
                    "ID": "purchasedates_have_purchase__date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data.purchasedate": {
                    "Target": {
                      "Entity": "sales_data.purchasedate"
                    }
                  },
                  "sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_purchasedate_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "sales_data.purchasedate.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_purchasedate_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "sales_data.purchasedate.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_purchasedate_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "sales_data.purchasedate.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "sales_data_purchasedate_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "Sales Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "sales_data.purchasedate.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "sales_data.purchasedate.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "81708589-96d5-4368-a227-efacde9d477c",
        "fromColumn": "purchase-date",
        "fromTable": "Sales Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bf45149b-c511-4d21-94d8-7f3987ee2650"
      },
      {
        "name": "AutoDetected_59ee6b49-b895-48b5-8723-d953d3348f15",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "sku",
        "fromTable": "Sales Data",
        "toColumn": "SKU (Amazon)",
        "toTable": "ASIN"
      },
      {
        "name": "ca67267f-3381-8d49-94da-bea4ab146d4c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ASIN",
        "fromTable": "ASIN",
        "toColumn": "ASIN",
        "toTable": "inventory"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_9c42aca5-93a0-4f45-865e-591d5a6048c7",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1d3509e0-0595-4c0f-9539-c4b05977456e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "01c806bc-5060-4598-baa6-7f70feb54f5f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "563e521f-96c3-43be-95e6-6b0fbdd71248",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "712185c9-c1a8-45c4-87af-a9f619a20dd8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c9c46d80-1ed1-4089-a92f-a0570c6cff66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9c5692a0-ef66-4a2f-8bb0-a57c69f70908",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8175ce96-bd59-4a47-9754-b2d28a4cd5d5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7d853e39-e232-4a1a-b682-03e63da60931",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d3300da1-f77e-4935-9a04-4a26907b81d6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "51f8a212-2e4b-42fb-a662-98d58c9e102f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a0c5176-7af8-497a-be60-3423406f6333",
                "ordinal": 3
              }
            ],
            "lineageTag": "c744bd01-8d21-4a2e-8f2b-b1a1454e363d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f1dc7a6d-083d-4ca1-b1e3-191986e1be4a",
        "partitions": [
          {
            "name": "DateTableTemplate_9c42aca5-93a0-4f45-865e-591d5a6048c7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ASIN",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SKU (Amazon)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7e4d20e-9b2f-4a2f-a570-9f2622a1acac",
            "sourceColumn": "SKU (Amazon)",
            "summarizeBy": "none"
          },
          {
            "name": "ASIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cd8e77f-5a0a-4be7-8820-6d917393b329",
            "sourceColumn": "ASIN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9d268a43-d57a-4e07-8939-ac2fabcc5ae6",
        "partitions": [
          {
            "name": "ASIN",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\Work Docs\\Power BI\\Supplements Sales Dashboard\\ASIN.xlsx\"), null, true),",
                "    Sheet2_Table = Source{[Item=\"Sheet2\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Sheet2_Table,{{\"SKU (Amazon)\", type text}, {\"ASIN\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "amazon-order-id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "lineageTag": "28590afa-0d1d-4394-be14-a227019199cd",
            "sourceColumn": "amazon-order-id",
            "summarizeBy": "none"
          },
          {
            "name": "purchase-date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "8e9401b9-75ad-422a-bb7b-306ee8c46acd",
            "sourceColumn": "purchase-date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bf45149b-c511-4d21-94d8-7f3987ee2650"
                },
                "isDefault": true,
                "relationship": "81708589-96d5-4368-a227-efacde9d477c"
              }
            ]
          },
          {
            "name": "buyer-email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2fdfe7d-efbc-4cc9-84ed-9f9de9fa3eae",
            "sourceColumn": "buyer-email",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45204769-9458-4a28-8085-48d50abb5e8d",
            "sourceColumn": "sku",
            "summarizeBy": "none"
          },
          {
            "name": "quantity-shipped",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "81fa03fc-eb54-4ba8-b954-b93b5f72e056",
            "sourceColumn": "quantity-shipped",
            "summarizeBy": "sum"
          },
          {
            "name": "currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f118aa5-d01e-491b-a625-d6c21cca52eb",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "item-price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1962b79b-8882-4d4a-914e-7af1b388d7d0",
            "sourceColumn": "item-price",
            "summarizeBy": "sum"
          },
          {
            "name": "ship-service-level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60b11688-a122-497a-8f6f-4e42415dd361",
            "sourceColumn": "ship-service-level",
            "summarizeBy": "none"
          },
          {
            "name": "ship-postal-code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36e67917-dd42-400f-b585-7292a2a77616",
            "sourceColumn": "ship-postal-code",
            "summarizeBy": "none"
          },
          {
            "name": "ship-country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbd71be8-a37b-4ccd-a6cc-4c27a474400f",
            "sourceColumn": "ship-country",
            "summarizeBy": "none"
          },
          {
            "name": "item-promotion-discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a44eba9c-966a-485a-b048-65f011ed1e7d",
            "sourceColumn": "item-promotion-discount",
            "summarizeBy": "sum"
          },
          {
            "name": "ship-promotion-discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fb671242-81fa-418e-ba56-d722f88f411a",
            "sourceColumn": "ship-promotion-discount",
            "summarizeBy": "sum"
          },
          {
            "name": "carrier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a185bc5-3721-43a9-b525-53cb011c0a0e",
            "sourceColumn": "carrier",
            "summarizeBy": "none"
          },
          {
            "name": "sales-channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "457f3e64-52ae-4cc5-9935-80f7ba874692",
            "sourceColumn": "sales-channel",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c66c681b-8d5e-4192-80e8-96a6d77934a7",
        "partitions": [
          {
            "name": "Sales Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\Work Docs\\Power BI\\Supplements Sales Dashboard\\Sales Data.xlsx\"), null, true),",
                "    #\"2170387053601845_Sheet\" = Source{[Item=\"2170387053601845\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"2170387053601845_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"amazon-order-id\", type text}, {\"purchase-date\", type datetime}, {\"buyer-email\", type text}, {\"sku\", type text}, {\"quantity-shipped\", Int64.Type}, {\"currency\", type text}, {\"item-price\", type number}, {\"ship-service-level\", type text}, {\"ship-postal-code\", type any}, {\"ship-country\", type text}, {\"item-promotion-discount\", type number}, {\"ship-promotion-discount\", type number}, {\"carrier\", type text}, {\"sales-channel\", type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"purchase-date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bf45149b-c511-4d21-94d8-7f3987ee2650",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2093305a-0fa0-43f8-9364-0704879e1cc3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1b77c06f-876b-4dbc-b524-d88d85102cd1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1e8d3132-5e8c-42bb-8380-a003dc935789",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0c8b557a-c8b7-40cf-830a-8b60c693cbe9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "15f97c45-1741-4b81-a12d-0d8a76c3e0f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "652a90e9-b23d-4b22-bca0-ee6bd7c71b89",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4b651121-a25d-47b9-877a-5f925c125104",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7eda15ac-a688-4de0-8f6c-848a1e49ccb4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "88d3f93d-a3b7-4817-9d05-c9bbbc996e51",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6b222479-6b12-4870-aab9-7d9b0c887c5e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4cb70187-b37d-4760-85f2-cdcb28d14d11",
                "ordinal": 3
              }
            ],
            "lineageTag": "ad692969-b22d-4239-b6e7-52ae926d701d"
          }
        ],
        "isHidden": true,
        "lineageTag": "ca23c855-f189-4493-b8f8-1132a2f0ee42",
        "partitions": [
          {
            "name": "LocalDateTable_bf45149b-c511-4d21-94d8-7f3987ee2650",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales Data'[purchase-date])), 1, 1), Date(Year(MAX('Sales Data'[purchase-date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "cfb22f83-e51b-4f02-8c9f-78ff5a9622d5",
        "measures": [
          {
            "name": "Total Earnings",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[quantity-shipped] * ('Sales Data'[item-price] - 'Sales Data'[item-promotion-discount])",
              ")"
            ],
            "lineageTag": "3d03355a-ec9d-499a-950c-2d0ea4eca0fd"
          },
          {
            "name": "Total Products Sold",
            "expression": "SUM('Sales Data'[quantity-shipped])",
            "formatString": "0",
            "lineageTag": "c742d1cb-f898-46b3-96e8-b535fd70e7c2"
          },
          {
            "name": "Total Inventory Products",
            "expression": "SUM(inventory[TOTAL INVENTORY Units])",
            "formatString": "0",
            "lineageTag": "5d0337c2-d4d9-4508-bc69-dbe9d7ad896b"
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "inventory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ASIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1148516-57be-460d-a1e5-fad6e3dd7d6d",
            "sourceColumn": "ASIN",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL INVENTORY Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bce8c83e-6cc9-4bbf-82bf-eaf05f03c5d6",
            "sourceColumn": "TOTAL INVENTORY Units",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "064c63ff-563c-4d08-9c05-62856be79b41",
        "partitions": [
          {
            "name": "inventory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Damyan\\Desktop\\Work Docs\\Power BI\\Supplements Sales Dashboard\\Inventory.xlsx\"), null, true),",
                "    inventory_Sheet = Source{[Item=\"inventory\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(inventory_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ASIN\", type text}, {\"TOTAL INVENTORY Units\", Int64.Type}}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Changed Type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"TOTAL INVENTORY Units\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}